# Generated by Django 2.1 on 2019-07-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeGrowth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstImage', models.ImageField(blank=True, upload_to='images/')),
                ('secondImage', models.ImageField(blank=True, upload_to='images/')),
                ('thirdImage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TreeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('addressline1', models.CharField(max_length=200)),
                ('addressline2', models.CharField(max_length=200)),
                ('distt', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('longitude', models.BigIntegerField()),
                ('latitude', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeName', models.CharField(max_length=100)),
                ('treeDescription', models.TextField(max_length=100)),
                ('treeAge', models.IntegerField()),
                ('growthTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('envEffects', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='treelocation',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreePlant.TreeType'),
        ),
        migrations.AddField(
            model_name='treelocation',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treegrowth',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TreePlant.TreeType'),
        ),
    ]
