# Generated by Django 2.1 on 2019-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreePlant', '0006_remove_treelocation_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treelocation',
            name='addressline1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='treelocation',
            name='addressline2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='treelocation',
            name='street',
            field=models.TextField(max_length=100),
        ),
    ]
