# Generated by Django 2.1 on 2019-07-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreePlant', '0009_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecatalog',
            name='leaf',
            field=models.CharField(default='qw', max_length=100),
        ),
        migrations.AddField(
            model_name='treecatalog',
            name='life',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='treecatalog',
            name='root',
            field=models.CharField(default='qw', max_length=100),
        ),
        migrations.AddField(
            model_name='treecatalog',
            name='shoot',
            field=models.CharField(default='qw', max_length=100),
        ),
        migrations.AddField(
            model_name='treecatalog',
            name='stem',
            field=models.CharField(default='qw', max_length=100),
        ),
    ]
