# Generated by Django 2.1 on 2019-07-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsCrowd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowduserprofile',
            name='typ',
            field=models.IntegerField(max_length=100),
        ),
    ]
