# Generated by Django 2.1 on 2019-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsCrowd', '0003_auto_20190718_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowduserprofile',
            name='typ',
            field=models.IntegerField(),
        ),
    ]
