# Generated by Django 2.1 on 2019-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(upload_to='images/teamProfile')),
                ('facebookLink', models.CharField(max_length=100)),
                ('twitterLink', models.CharField(max_length=100)),
                ('linkedInLink', models.CharField(max_length=100)),
            ],
        ),
    ]
