# Generated by Django 2.1 on 2019-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourservices_teaminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationName', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('maplocation', models.CharField(max_length=600)),
                ('orgLogo', models.ImageField(default=True, upload_to='images/OurPartner/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide1', models.ImageField(upload_to='images/slider/')),
                ('slide2', models.ImageField(upload_to='images/slider/')),
                ('slide3', models.ImageField(upload_to='images/slider/')),
            ],
        ),
    ]
