# Generated by Django 2.1 on 2019-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190714_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='amountDonated',
            field=models.FloatField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='hey', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, default='hey', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review',
            field=models.TextField(default='hey'),
        ),
    ]
