# Generated by Django 2.1 on 2019-07-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190715_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='amountRecieve',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='totalTree',
        ),
    ]
