# Generated by Django 2.1 on 2019-07-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190716_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
