# Generated by Django 2.1 on 2019-07-17 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapling',
            name='numOfTree',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sapling',
            name='us',
            field=models.OneToOneField(default=55, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
