# Generated by Django 2.1 on 2019-07-17 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_auto_20190718_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapling',
            name='us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
